# Generated by Django 5.0.4 on 2026-05-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_application_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
